### ISSUE TITLE
"Unknown" games

### ISSUE THREAD

**Issue by MrJabberwock** [nyash-qq/galaxy-plugin-twitch#11]
I have 15 "Unknown" games showing in my Twitch library. I don't know if there's a pattern or relation to why these are unknown/missing, but here's my list of titles showing as "Unknown game" in GOG:

1. \>observer_
2. 10 Second Ninja X
3. AER Memories of Old
4. Chicken Assassin
5. Devil May Cry HD Collection
6. Pulstar
7. Pumped BMX
8. Samurai Showdown II
9. System Shock: Enhanced Edition
10. The Adventure Pals
11. The Bridge
12. The Last Blade
13. The Original Strife: Veteran Edition
14. Twinkle Star Sprites
15. Wizardry 6: Bane of the Cosmic Forge

![GalaxyClient_JX2NcGuoMB](https://user-images.githubusercontent.com/17773362/64909888-0fa07f00-d6d7-11e9-849f-87e21a27058e.png)

**Comment by nyash-qq** [comment]
`Unknown` games is the GLX client failed to match your games against its db. So plugin did return them, you just see this `Unknown` placeholder instead of real media. Feel free to report missing games to GOG with `coghweel menu` -> `Report Issue`.
If you would have missing games, then it would be either:
- the plugin failed to find the game (you can check if the game appears in  `c:\ProgramData\GOG.com\Galaxy\logs\plugin-twitch-8b831aed-dd5f-c0c5-c843-41f9751f67a2.log`, if not, I'd need some more info)
-or the GLX filtering/hiding them (then you also need to report this to GOG)

**Comment by Danyelalejandro** [comment]
I have the same problem as @MrJabberwock, I checked the log and the games does appear. What does this means?
[plugin-twitch-8b831aed-dd5f-c0c5-c843-41f9751f67a2.log](https://github.com/nyash-qq/galaxy-plugin-twitch/files/3613248/plugin-twitch-8b831aed-dd5f-c0c5-c843-41f9751f67a2.log)

**Comment by MrJabberwock** [comment]
Seems to have resolved itself later that same day.
