### ISSUE TITLE
Amazon and Twitch library are duplicated

### ISSUE THREAD

**Issue by Danyelalejandro** [nyash-qq/galaxy-plugin-twitch#12]
Hello
I erased the plugin for Amazon and installed the Twitch one and, still, both libraries seems to be duplicated.
The install option is still not working

**Comment by nyash-qq** [comment]
I'm aware of disabled `Install`. This is still by the GLX side and there is nothing I can do about. You can try to force them by sending a feedback via GLX client :)
As for duplicated games, before erasing a plugin, you should first `Disconnect` it in settings, otherwise your game library for that platform stays in GOG backend service. There should be an `remove platform data` button or something, but it's not there yet unfortunately.
The easiest now is to:
1. `Disconnect` Twitch plugin
2. set `"platform": "amazon"` in the `%LOCALAPPDATA%\GOG.com\Galaxy\plugins\installed\twitch_8b831aed-dd5f-c0c5-c843-41f9751f67a2\manifest.json`
3. wait a couple of seconds so the library is synchronized
4. `Disconnect` `Amazon` plugin, so data is removed from GOG servers
5. revert platform back to `"platform": "twitch"`

Now you should only have Twitch games

**Comment by Danyelalejandro** [comment]
Yes. After 2-3 tries it worked. Thank you so much!!!
I have reported the "install" issue through GLX client. Hoping more people reports it too so they can hear us.
