### ISSUE TITLE
'All games' tab no longer loads after adding integration

### ISSUE THREAD

**Issue by effcol** [nyash-qq/galaxy-plugin-twitch#6]
After adding this integration and logging in, whenever I try and access the 'all games' section to see every single game I have, nothing loads in it, and if I then go to another tab like 'installed' and back again, then won't even try and load the 'all games' section, it just stays within whatever section I was in before.

All the games were imported, if I go to the 'Amazon' tab all the games I have are showing, and if I go to 'Installed' it shows all the twitch games I have installed, so it's only affecting the 'all games' section.

This issue appeared after specifically installing this integration so I can only narrow it down to this having introducing the bug.

**Comment by MarcD2K20** [comment]
I also experienced this issue, but when adding the Humble Bundle plugin, after adding the Twitch one, so i don't think it's necessarily related to this one in particular. Have you added any other community integrations like humble bundle etc? I am wondering if it is because none of them have a name in the library, it somehow messes up the program's ability to query 'all games'

**Comment by effcol** [comment]
The issue seemed to have cleared itself up not, maybe gog got an update i'm not sure, either way seems to be fixed :) might have been relate to them having no names, seems more likely gog fixed something on their end :S Either way, seems fixed for me now :)

**Comment by nyash-qq** [comment]
I'm glad this is fixed, but it's an issue by GOG's side anyway, not the plugin.
